name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build github.com/downflux/go-geometry
      run: go build -v github.com/downflux/go-geometry/...

    - name: Vet github.com/downflux/go-geometry
      run: go vet -v github.com/downflux/go-geometry/...

    - name: Test github.com/downflux/go-geometry
      run: go test -v github.com/downflux/go-geometry/... -bench .
